language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script: pytest --cov=group_lasso
after_success: coveralls
