sudo: false
language: python
python:
  - "3.5"
# command to install dependencies
install:
before_script:
  - pip install tox-travis
  - pip install coveralls
# command to run tests
script: pytest --cov=group_lasso
after_success: coveralls
